### ISSUE TITLE
using the gem on heroku 

### ISSUE THREAD

**Issue by johnkyony** [evansobkowicz/awesome-share-buttons#1]
Hey I really love this gem , I am just having an issue with it , the gem works perfectly when i am working on my dev enviroment but when i push up to heroku the icons can not be seen , do you know a work around it @evansobkowicz

**Comment by evansobkowicz** [comment]
@johnkyony I've updated the asset paths to use asset_path(). Hopefully that fixes your problem, if not let me know and I can look at it again.

**Comment by johnkyony** [comment]
@evansobkowicz Thanks I shall update my gem file and then try the fix and let you know.
